Milestone4 styling
TheLuisAbarca/bookstore-react_redux pull request #4
Opened 2022-01-21 21:55 UTC by TheLuisAbarca

## Styling

> In this branch, I have made the following changes:

1. Implement Styling for the project.
2. Fix StyleLint linters.
3. Add picture to README file.

2022-01-21 23:37 UTC, Lameck1 requested changes
Hi, @TheLuisAbarca, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-21 23:37 UTC, Lameck1 commented on src/components/RoundProgressBar.module.css
> +}
Well done for the styling so far. Since it is a strict requirement to follow the design guideline and implement the design as provided, we will need to do some adjustments to our styling.

- [ ] Let's start with this section. Please compare the screenshots below and make the necessary adjustments. The progress bar and the text should be side by side.

 | THE DESIGN | YOUR IMPLEMENTATION |
 | --- | --- |
 | ![image](https://user-images.githubusercontent.com/45002654/150610261-d5b7c37b-afb1-4975-ab16-5bb65063d575.png) | ![image](https://user-images.githubusercontent.com/45002654/150610278-aee89f2a-c717-4d49-a110-1c62cb40ad6a.png) |
 
 The font family for this section, according to the design should be:
 ```CSS
 font-family: Montserrat;
 ```
 
 Please take care of refactoring the font family too.

2022-01-21 23:37 UTC, Lameck1 commented on src/components/Navbar.module.css
> +}
- [ ] For the Nav Links, we need to take care of the font family and the text capitalization. 

 | THE DESIGN | YOUR IMPLEMENTATION |
 | --- | --- |
 | ![image](https://user-images.githubusercontent.com/45002654/150610904-b92b6570-b7d2-40a6-904b-e251e24c8c3b.png) | ![image](https://user-images.githubusercontent.com/45002654/150610927-4982cfaf-c61d-452b-bbb2-17a6a4a83cee.png) |
 
 The font family for this section, according to the design should be:
 ```CSS
 font-family: Montserrat;
 ```
 
 Please style the texts as in the provided design.

2022-01-21 23:37 UTC, Lameck1 commented on src/components/BookElement.module.css
> +}
- [ ] For this section, we need to take care of the font family and general font styling i.e color of text. 

 | THE DESIGN | YOUR IMPLEMENTATION |
 | --- | --- |
 | ![image](https://user-images.githubusercontent.com/45002654/150611679-b7c61784-9a6f-4978-aafd-1c8f815cdc24.png) | ![image](https://user-images.githubusercontent.com/45002654/150612085-275cde19-7a9b-49fa-80ac-837899a44202.png) |
 
 Needed rules for the book title:
 ```CSS
 font-family: RobotoSlab;
 ```
 
 Needed rules for category:
 ```CSS
 font-family: Montserrat;
 color: #121212
 ```
 
 Needed rules for author and the three button below the author:
 ```CSS
 font-family: RobotoSlab;
 color: #4386bf
 ```
 
 Please style the texts as in the provided design.

2022-01-21 23:37 UTC, Lameck1 commented on src/components/BookElement.module.css
> +}
- [ ] For this section we need to take care of the font family and Capitalization of text. 

 | THE DESIGN | YOUR IMPLEMENTATION |
 | --- | --- |
 | ![image](https://user-images.githubusercontent.com/45002654/150612507-774f1ffb-4ce2-40d8-9c9e-0d663b25d207.png) | ![image](https://user-images.githubusercontent.com/45002654/150612530-1d4c5992-7e64-43e3-8e62-ec72323d0a48.png) |
 
 - Font family for this whole section should be:
 ```CSS
 font-family: RobotoSlab;
 ```
 
 - Font color for current lesson:
 ```CSS
 color: #121212
 ```
 
- Texts for `CURRENT CHAPTER` and `UPDATE PROGRESS` should be in all uppercase.
 
 Please style the texts as in the provided design.

2022-01-21 23:37 UTC, Lameck1 commented on src/components/BookForm.module.css
> +}
- [ ] Text in this button should be all uppercase. Take care of the font family too. 
 
 - Required rules:
 ```CSS
 font-family: RobotoSlab;
 ```
 
 Please style as in the provided design.

2022-01-21 23:37 UTC, Lameck1 commented on src/components/BookForm.module.css
> +}
- [ ] Please apply a font family of `font-family: Montserrat;` to this `h2` just like in the design.

2022-01-22 05:37 UTC, TheLuisAbarca commented on src/components/RoundProgressBar.module.css
> +}
Thanks for your kind and specific feedback @Lameck1. It is really helpful! The corrections have been made on commits 2a1c5d3 and 07bfe3a.

2022-01-22 05:38 UTC, TheLuisAbarca commented on src/components/Navbar.module.css
> +}
Thanks for your kind and specific feedback @Lameck1. It is really helpful! The corrections have been made on commits 2a1c5d3.

2022-01-22 05:43 UTC, TheLuisAbarca commented on src/components/BookElement.module.css
> +}
Thanks for your kind and specific feedback @Lameck1. It is really helpful! The corrections have been made on commits 3547e6d.

2022-01-22 05:44 UTC, TheLuisAbarca commented on src/components/BookForm.module.css
> +}
Thanks for your kind and specific feedback @Lameck1. It is really helpful! The corrections have been made on commits 04ddfa3.

2022-01-22 05:44 UTC, TheLuisAbarca commented on src/components/BookForm.module.css
> +}
Thanks for your kind and specific feedback @Lameck1. It is really helpful! The corrections have been made on commits c3495f4.

2022-01-22 05:53 UTC, BrianSammit approved these changes
# STATUS: APROVED :green_circle: :clap: 

Hello @TheLuisAbarca, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-22 20:45 UTC, merged